### PR TITLE
Make `have_received` work without relying upon rspec-expectations.

### LINKED ISSUE #967: have_received matcher fails with Minitest
I'm trying to use rspec-mock's spies in a Minitest (**not** `Minitest::Spec`) project and am running into an error that I don't know how to solve.

I'm using Minitest 5.7, rspec-mocks 3.2.1, and Ruby 2.1.3p342.

As near as I can tell, I'm not running into any conflicts between Minitest and rspec-mocks.  When I trace through the code, I seem to be hitting only methods in rspec-mocks.

When I run the example below, I get the following error. If I run an equivalent example written with RSpec, everything works as expected.

```
 1) Error:
SpyTest#test_accepts_invitation:
NoMethodError: undefined method `setup_expectation' for #<RSpec::Mocks::Matchers::HaveReceived:0xb8dae0cc>
    /usr/local/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.2.1/lib/rspec/mocks/targets.rb:45:in `define_matcher'
    /usr/local/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.2.1/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
    spies.rb:33:in `test_accepts_invitation'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

```ruby
require "minitest/autorun"
require "rspec/mocks"

class User
  def accept_invitation(invitation)
    invitation.accept
  end
end

module RSpecMocksIntegration
  include ::RSpec::Mocks::ExampleMethods

  def before_setup
    ::RSpec::Mocks.setup
    super
  end

  def after_teardown
    super
    ::RSpec::Mocks.verify
  ensure
    ::RSpec::Mocks.teardown
  end
end

class SpyTest < Minitest::Test
  include RSpecMocksIntegration
  
  def test_accepts_invitation
    invitation = spy("invitation")
    user = User.new
    user.accept_invitation(invitation)
    expect(invitation).to have_received(:accept)
  end
end
```

### PR DESCRIPTION
**Pull request by myronmarston**
Fixes #967 and #968.

@randycoulman -- want to try this out?

### CODE REVIEW

File: spec/rspec/mocks/matchers/have_received_spec.rb [hunk 1]
```diff
@@ -1,6 +1,26 @@
 module RSpec
   module Mocks
-    RSpec.describe Matchers::HaveReceived do
+    # This shared exampe group is highly unusual as it is used to test how
```
Comment (randycoulman) [inline spec/rspec/mocks/matchers/have_received_spec.rb]: `exampe` => `example`

**Comment by randycoulman** [comment]
I've tested this with my example case, and it seems to work just fine.  Note the one typo I pointed out.

Making rspec-mocks fully work without rspec-expectations is a much better solution than just making it clear that parts of it don't work, so I much prefer this solution to my workaround.

I missed the `outside_rspec` features when I did my PR, so I'm glad that's there.  The way you wrote the RSpec specs for this is impressive and a little bit scary, but I'm glad you figured out a way to do it.  The rest of the code seems relatively straightforward.

File: spec/rspec/mocks/matchers/have_received_spec.rb (hunk 1 above)
Comment (myronmarston) [inline spec/rspec/mocks/matchers/have_received_spec.rb]: Thanks, fixed.

**Comment by myronmarston** [comment]
> The way you wrote the RSpec specs for this is impressive and a little bit scary, but I'm glad you figured out a way to do it.

Yep.  Felt like a hack, and it's probably not the way I would do it if I was writing all the tests from scratch...but it was the easiest way I could find to re-use the existing specs.

Thanks for trying this out :).

File: spec/rspec/mocks/matchers/have_received_spec.rb [hunk 2]
```diff
@@ -1,6 +1,26 @@
...
+    #   the other forms.
+    # * All normal expectations must use `_expect`, not `expect`. Expectations
+    #   for `have_received` should use `expect`.
+    RSpec.shared_examples_for Matchers::HaveReceived do
+      # Make rspec-expectations' `expect` available via an alias so that when
+      # this group is included below in a context that simulates rspec-expectations
+      # not being loaded by using rspec-mocks' `expect` instead of rspec-expectations'
+      # `expect`, we still have a way to use the expectations one for normal expectations.
+      # In this group, all normal expectations should use `_expect` instead of `expect`.
+      alias _expect expect
```
Comment (samphippen) [inline spec/rspec/mocks/matchers/have_received_spec.rb]: Would making this name longer (e.g. `rspec_expectations_expect`) or changing the other one to be "mocks_expect" add clarity here?

**Comment by samphippen** [comment]
One minor quibble but I'm otherwise happy :+1:

File: spec/rspec/mocks/matchers/have_received_spec.rb (hunk 2 above)
Comment (myronmarston) [inline spec/rspec/mocks/matchers/have_received_spec.rb]: > Would making this name longer (e.g. `rspec_expectations_expect`)

I think I'd want a longer name if it wasn't localized to this one file.  `rspec_expectations_expect` is soo much longer that I prefer the terser `_expect`.

> or changing the other one to be "mocks_expect" add clarity here?

I thought about that, but there's a downside to that approach: if we wrote a new spec, and forgot to use `mocks_expect` for `have_received`, the spec would pass even though it wasn't testing what we intend it to.  Contrast that to when we write a new spec and forget to use `_expect` over `expect`: we'll get a failure and we'll be forced to fix it.

I much prefer things setup so that when we forget it fails rather than getting a false positive.
