### PR TITLE
Fix issue where expect_any_instance_of could not constrain arguments on a message chain

### LINKED ISSUE #1155: Undefined method `include?' for nil:NilClass when using expect_any_instance_of(Klass).to receive_message_chain(msgs).with(arg)
I have the following issue with rspec-mocks-3.6.0.beta2:
```ruby
  it 'test expect_any_instance_of to receive_message_chain' do
    class Klass
    end
    expect_any_instance_of(Klass).to receive_message_chain('message1.message2').with('some args')
  end

```

when I run the test
`bundle exec rspec spec/carrierwave/storage/flickr_spec.rb:163 -b`

I get this error:
```
CarrierWave::Storage::Flickr
  test expect_any_instance_of to receive_message_chain (FAILED - 1)

Failures:

  1) CarrierWave::Storage::Flickr test expect_any_instance_of to receive_message_chain
     Failure/Error: expect_any_instance_of(Klass).to receive_message_chain('message1.message2').with('some args')

     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/stub_chain.rb:41:in `verify_invocation_order'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/chain.rb:103:in `record'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/chain.rb:28:in `block in record'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/chain.rb:85:in `with'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/proxy.rb:110:in `block in method_missing'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/proxy.rb:110:in `map'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/proxy.rb:110:in `method_missing'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/matchers/expectation_customization.rb:15:in `playback_onto'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/matchers/receive_message_chain.rb:66:in `block in replay_customizations'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/matchers/receive_message_chain.rb:65:in `each'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/matchers/receive_message_chain.rb:65:in `replay_customizations'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/matchers/receive_message_chain.rb:45:in `setup_any_instance_expectation'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/targets.rb:46:in `define_matcher'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/targets.rb:10:in `block in delegate_to'
     # ./spec/carrierwave/storage/flickr_spec.rb:166:in `block (2 levels) in <top (required)>'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:254:in `instance_exec'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:254:in `block in run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:496:in `block in with_around_and_singleton_context_hooks'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:453:in `block in with_around_example_hooks'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/hooks.rb:464:in `block in run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/hooks.rb:464:in `run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:453:in `with_around_example_hooks'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:496:in `with_around_and_singleton_context_hooks'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example.rb:251:in `run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example_group.rb:623:in `map'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/example_group.rb:589:in `run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:118:in `map'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/configuration.rb:1875:in `with_suite_hooks'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/reporter.rb:78:in `report'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:112:in `run_specs'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:87:in `run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:71:in `run'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-core-3.6.0.beta2/exe/rspec:4:in `<top (required)>'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/bin/rspec:23:in `load'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/bin/rspec:23:in `<main>'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/bin/ruby_executable_hooks:15:in `eval'
     # /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/bin/ruby_executable_hooks:15:in `<main>'
```

Seems like that the error happens in
```ruby
From: /Users/Hirurg103/.rvm/gems/ruby-2.2.4@carriervawe-flickr/gems/rspec-mocks-3.6.0.beta2/lib/rspec/mocks/any_instance/expect_chain_chain.rb @ line 25:
Owner: RSpec::Mocks::AnyInstance::ExpectChainChain
Visibility: private
Number of lines: 7

def invocation_order
  @invocation_order ||= {
    :and_return => [nil],
    :and_raise => [nil],
    :and_yield => [nil]
  }
end
```

I thought that this issue has been fixed in #1061, but seems like that hasn't. Could you please help me to get this test case falling normally. Thanks!

### PR DESCRIPTION
**Pull request by JonRowe**
Fixes #1155.

### CODE REVIEW

File: spec/rspec/mocks/any_instance_spec.rb [hunk 1]
```diff
@@ -123,6 +123,11 @@ def private_method; :private_method_return_value; end
               expect(klass.new.one.plus(1)).to eq(2)
               expect(klass.new.one.plus(2)).to eq(3)
             end
+
+            it 'can use a chain of methods to perform an expectation' do
+              expect_any_instance_of(klass).to receive_message_chain('message1.message2').with('some args')
```
Comment (myronmarston) [inline spec/rspec/mocks/any_instance_spec.rb]: I didn't realize we supported `with` with message chains.  Seems weird, since `with` is specifying something about a particular message but message chains are about multiple messages...

That said, I can see that works for normal doubles.

File: lib/rspec/mocks/any_instance/expect_chain_chain.rb [hunk 2]
```diff
@@ -24,6 +24,7 @@ def create_message_expectation_on(instance)
 
         def invocation_order
           @invocation_order ||= {
+            :with => [nil],
             :and_return => [nil],
             :and_raise => [nil],
             :and_yield => [nil]
```
Comment (myronmarston) [inline lib/rspec/mocks/any_instance/expect_chain_chain.rb]: While we're in here, are there any other methods like `with` that is supported by `expect(...).to receive_message_chain` but not `expect_any_instance_of(...).to receive_message_chain`?

File: spec/rspec/mocks/any_instance_spec.rb [hunk 3]
```diff
@@ -123,6 +123,11 @@ def private_method; :private_method_return_value; end
               expect(klass.new.one.plus(1)).to eq(2)
               expect(klass.new.one.plus(2)).to eq(3)
             end
+
+            it 'can use a chain of methods to perform an expectation' do
```
Comment (myronmarston) [inline spec/rspec/mocks/any_instance_spec.rb]: Isn't the behavior this spec is about the fact that `with` can be used with any instance?  Would be nice for the docstring to explain that if it's the case...

File: spec/rspec/mocks/any_instance_spec.rb [hunk 4]
```diff
@@ -123,6 +123,11 @@ def private_method; :private_method_return_value; end
...
+              expect_any_instance_of(klass).to receive_message_chain('message1.message2').with('some args')
+              klass.new.message1.message2
```
Comment (myronmarston) [inline spec/rspec/mocks/any_instance_spec.rb]: Should this be `klass.new.message1.message2('some args')`?

Comment (JonRowe) [inline spec/rspec/mocks/any_instance_spec.rb]: It should indeed, fixed.

File: lib/rspec/mocks/any_instance/expect_chain_chain.rb (hunk 2 above)
Comment (JonRowe) [inline lib/rspec/mocks/any_instance/expect_chain_chain.rb]: You make an excellent point, maybe we should change how this is accessed instead...

File: spec/rspec/mocks/any_instance_spec.rb (hunk 1 above)
Comment (JonRowe) [inline spec/rspec/mocks/any_instance_spec.rb]: Yeah and it works for `allow_any_instance_of` :/

File: spec/rspec/mocks/any_instance_spec.rb (hunk 3 above)
Comment (JonRowe) [inline spec/rspec/mocks/any_instance_spec.rb]: We've specced that elsewhere, this is specifically for demonstrating `expect_any_instance_of` works :/

File: lib/rspec/mocks/any_instance/expect_chain_chain.rb (hunk 2 above)
Comment (JonRowe) [inline lib/rspec/mocks/any_instance/expect_chain_chain.rb]: I've pushed up a refactor, see what you think, it will at least surface the true error rather than showing the `include?` one.

File: lib/rspec/mocks/any_instance/expect_chain_chain.rb [hunk 5]
```diff
@@ -23,11 +23,7 @@ def create_message_expectation_on(instance)
         end
 
         def invocation_order
-          @invocation_order ||= {
-            :and_return => [nil],
-            :and_raise => [nil],
-            :and_yield => [nil]
-          }
+          @invocation_order ||= {}
```
Comment (myronmarston) [inline lib/rspec/mocks/any_instance/expect_chain_chain.rb]: Seems kindy silly to cache an empty hash.   And actually, all of the `invocation_order` methods return static hashes that are never different for different instances.  WDYT about refactoring to move them into a frozen constant?  If it helps implementation it could always keep the instance method (which would just return the constant) but that way we don't waste memory by creating new copies of the exact same hashes.

File: lib/rspec/mocks/any_instance/stub_chain.rb [hunk 6]
```diff
@@ -27,7 +27,6 @@ def create_message_expectation_on(instance)
 
         def invocation_order
           @invocation_order ||= {
-            :with => [nil],
             :and_return => [:with, nil],
             :and_raise => [:with, nil],
             :and_yield => [:with, :and_yield, nil],
```
Comment (myronmarston) [inline lib/rspec/mocks/any_instance/stub_chain.rb]: Are the `nil` values in these arrays still needed given your change below to use `fetch` with a fallback of `[nil]`.

File: lib/rspec/mocks/any_instance/stub_chain.rb [hunk 7]
```diff
@@ -38,7 +37,7 @@ def invocation_order
         end
 
         def verify_invocation_order(rspec_method_name, *_args, &_block)
-          return if invocation_order[rspec_method_name].include?(last_message)
+          return if invocation_order.fetch(rspec_method_name, [nil]).include?(last_message)
```
Comment (myronmarston) [inline lib/rspec/mocks/any_instance/stub_chain.rb]: Can you add a spec showing what happens as a result of this change, where it fails in an expected way instead of the confusing "Undefined method `include?`" error?

File: lib/rspec/mocks/any_instance/stub_chain.rb (hunk 6 above)
Comment (JonRowe) [inline lib/rspec/mocks/any_instance/stub_chain.rb]: Yes, nil marks the end of the chain.

File: lib/rspec/mocks/any_instance/stub_chain.rb (hunk 7 above)
Comment (JonRowe) [inline lib/rspec/mocks/any_instance/stub_chain.rb]: No because that should never happen, and I can't think of any remaining scenarios where it would happen, but after removing the "empty" values from the hashes this change was necessary to turn the build back to green, does that suffice?

File: lib/rspec/mocks/any_instance/expect_chain_chain.rb (hunk 5 above)
Comment (JonRowe) [inline lib/rspec/mocks/any_instance/expect_chain_chain.rb]: Yeah ok, done.

File: spec/rspec/mocks/any_instance_spec.rb (hunk 3 above)
Comment (myronmarston) [inline spec/rspec/mocks/any_instance_spec.rb]: Given this is the `any_instance_spec.rb` file, isn't the entire file about demonstrating that `expect_any_instance_of`?  I thought that what's unique about this spec example vs the others in this file is that it uses `receive_message_chain(...).with(...)` so it seems like the doc string should call that out.

Comment (JonRowe) [inline spec/rspec/mocks/any_instance_spec.rb]: Most of this file uses `allow_any_instance_of` so this spec is calling out that it also works with an expectation... eg.`expect_any_instance_of`

Comment (JonRowe) [inline spec/rspec/mocks/any_instance_spec.rb]: Merged as you said this wasn't a blocker, if you can come up with an improved doc string I'm happy to just update it
